services:
  database:
    image: postgres:16
    container_name: race-query-service-db
    restart: always
    environment:
      POSTGRES_USER: raceadmin
      POSTGRES_PASSWORD: racing123
      POSTGRES_DB: trail-race
    ports:
      - "5432:5432"
    volumes:
      - race-query-data:/var/lib/postgresql/data
    networks:
      - race-query-network
  pubsub:
    image: redis:7-alpine
    container_name: race-messaging-service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - race-messaging-data:/data
    networks:
      - race-messaging-network


volumes:
  race-query-data:
  race-messaging-data:

networks:
  race-query-network:
  race-messaging-network: