name: CI Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subproject:
          - command-service
          - query-service

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          #TODO add caching of dependencies

      - name: Build the application
        run: make build-${{ matrix.subproject }}

      - name: Run tests
        run: make test-${{ matrix.subproject }}

      #TODO add sonar, jacoco, deployment...